# Generated by Django 3.0.4 on 2021-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Name')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/images', verbose_name='Image')),
                ('ssc_marks', models.IntegerField(default=0, verbose_name='SSC Marks')),
                ('inter_marks', models.IntegerField(default=0, verbose_name='Inter Marks')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100, null=True, verbose_name='Card Title')),
                ('card_text', models.CharField(max_length=100, null=True, verbose_name='Card Text')),
                ('card_status', models.BooleanField(default=True)),
                ('card_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
