# Generated by Django 3.0.7 on 2020-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100, null=True, verbose_name='Card Title')),
                ('card_text', models.CharField(max_length=100, null=True, verbose_name='Card Text')),
                ('card_status', models.BooleanField(default=True)),
                ('card_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
