# Generated by Django 3.0.4 on 2021-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
